hob_nob/config/routes.rb
Rails.application.routes.draw do

  match "/404", :to => "errors#not_found", :via => :all
  
  match "/500", :to => "errors#internal_server_error", :via => :all


  
mount Ckeditor::Engine => '/ckeditor'
devise_for :users
as :user do
  get 'passwords/change_password' => 'devise/passwords#edit'
  put 'passwords' => 'devise/passwords#update'
end
#root "admin/dashboards#index"
root "admin/homes#index"
get 'back' => 'application#back'

resources :custom_pages

resources :events, :controller => "microsites", :as => "microsites"
resources :events do
  resources :custom_pages
end

namespace :admin do
  get 'bee_editor' => 'bee_editors#index'
  get '/mobile_applications/:mobile_application_id/success' => 'external_login#show'
  get '/events/:event_id/success' => 'user_registrations#show'
  get '/unsubscribes/success' => 'unsubscribes#show'
  get '/unsubscribes' => 'unsubscribes#index'
  get 'bee_editor/token' => 'bee_editors#token'
  get 'bee_editor/template' => 'bee_editors#template'
    
  # get '/check_email_existance' => 'users#check_email_existance'
  resources :time_zones, :notification_action_changes
  resources :dashboards, :themes, :manage_users, :users, :roles, :homes, :smtp_settings, :log_changes
  resources :profiles, :manage_mobile_apps, :downloads, :external_login, :prohibited_accesses, :change_roles, :icon_libraries
  resources :licensees do
    resources :clients    
  end
  resources :clients do
    resources :users, :marketing_apps
    resources :mobile_applications do
      resources :push_pem_files
    end
    resources :event_groups
    resources :events
    resources :fonts, except: [:show, :edit, :update]
  end
  resources :mobile_applications do
    resources :external_login
  end

  resources :events do
    resources :microsites do
      resources :microsite_look_and_feels, :microsite_features, :microsite_menus, :microsite_sequences
    end
  end

  resources :events do
    resources :abouts, :event_highlights, :emergency_exits, :themes, :sequences,:leaderboards, :chats, :invitee_groups, :qr_code_scanners, :qr_code_texts, :warehouse_timers,:qna_walls,:conversation_walls,:poll_walls,:quiz_walls, :activity_feeds, :feedback_forms, :export_qr_codes, :badge_pdfs, :microsites
    resources :speakers, :attendees, :invitees, :agendas, :conversations, :users, :notifications
    resources :event_features, :menus, :faqs, :images, :highlight_images, :feedbacks, :sponsors, :qnas, :feedbacks
    resources :e_kits, :contacts, :panels, :imports, :user_registrations
    resources :groupings, :exhibitors, :manage_feature_status, :analytics, :registration_settings, :custom_page1s, :custom_page2s, :custom_page3s, :custom_page4s, :custom_page5s, :invitee_datas,:my_travels,:manage_invitee_fields,:qna_settings, :qnas, :user_qnas, :feedbacks,:registration_look_and_feels,:registration_details,:auto_status_emails,:telecaller_accessible_columns,:telecaller_dashboards,:telecaller_groups,:campaign_details,:track_links ,:venue_sections,:invitee_accesses,:invitee_searches, :qr_scanner_details,:registration_statistics,:onsite_registrations,:maps, :folders, :consent_questions, :onsite_accessible_columns
    resources :custom_page6s, :custom_page7s, :custom_page8s, :custom_page9s, :custom_page10s, :telecaller_searchs
    resources :telecaller_invitees, :import_data_api
    resources :multi_lng_events, :unsubscribes, :log_changes
    # resources :feedback_forms do
    #   resources :feedbacks
    # end
    resources :feedback_forms,:feedbacks
    
    resources :telecallers do
      collection do
        get :attended_records
      end
    end

    resources :polls do
      resources :user_polls
    end

    resources :quizzes do
      resources :user_quizzes
    end

    # resources :invitee_datas do
    #   collection do
    #     post 'update_details'
    #   end
    # end

    resources :user_polls, :user_quizzes, :user_feedbacks, :likes, :comments

    resources :mobile_applications do
      resources :store_infos
      resources :mobile_consent_questions, :consent_question_look_and_feels
    end  
    resources :awards do
      resources :winners 
    end
    resources :invitee_structures do
      resources :invitee_datas
    end
    resources :registrations
    get '/user_qnas/new/:rid/:sid' => 'user_qnas#new', :as => "receiver_qnas"
    resources :campaigns do
      resources :edms do
        put :toggle_tele_assigned, on: :member
      end
    end
    resources :track_link_users
  end

  # resources :imports
end
# resources :events do
#   resources :microsites 
# end

get "/api/v1/activity_feeds?event_id=:event_id&social=true" => redirect("/api/v1/events/:event_id/social_feeds")
  namespace :api do
    namespace :v1 do
      get 'tokens/destroy_token' => 'tokens#destroy_token', defaults: {format: 'json'}
      post 'tokens/get_key' => 'tokens#get_key'#, defaults: {format: 'json'}
      get 'tokens/check_token' => 'tokens#check_token', defaults: {format: 'json'}
      post 'tokens/user_sign_up' => 'tokens#user_sign_up', defaults: {format: 'json'}
      post 'tokens/facebook_authentication' => 'tokens#facebook_authentication', defaults: {format: 'json'}
      post 'tokens/twitter_authentication' => 'tokens#twitter_authentication', defaults: {format: 'json'}
      resources :events do 
        post 'delete_mobile_data', on: :collection 
        resources :chats do 
          post 'update_chat_read_status', on: :collection # method used for update msg read status for api.
        end
        resources :invitee_chats,:social_feeds  
      end
      resources :tokens, :social_media_authentications, :abouts, :agendas, :speakers, :invitees, :leaderboards, :attendees, :images, :ratings, defaults: {format: 'json'} 
      resources :faqs, :notifications, :conversations, :comments, :qnas, :polls,:invitee_trackings, defaults: {format: 'json'}
      resources :awards, :event_features, :sponsors, :likes, :notes, :user_feedbacks,:e_kits, :mobile_applications, :passwords, :my_travels, defaults: {format: 'json'}
      resources :activity_feeds,:visitor_registrations, :mobile_consent_question_answers
    end
    namespace :v2 do
      resources :events
    end
    namespace :v3 do
      resources :events
    end
    namespace :v4 do
      resources :events
      resources :e_kits
    end
    namespace :v5 do
      resources :events, :conversations, :images, :leaderboards, :invitees
    end
  end
end

hob_nob/app/models/event_group.rb
class EventGroup < ActiveRecord::Base
  resourcify
  belongs_to :client
  default_scope { order('created_at desc') }

  def self.search(params, event_groups)
    keyword = params[:search][:keyword]
    event_groups = event_groups.where("name like (?)", "%#{keyword}%")if keyword.present?
    event_groups 
  end
end

hob_nob/app/controllers/admin/event_groups_controller.rb
class Admin::EventGroupsController < ApplicationController
  layout 'admin'

  # load_and_authorize_resource
  before_filter :authenticate_user
   before_filter :authorize_event_role, :except => [:index,:new,:create,:edit,:update,:show,:destroy]#, :if => Proc.new{params[:event_id].present?}
  before_filter :authorize_client_role, :find_client_association#, :only => [:index, :show, :edit, :update], :if => Proc.new{params[:client_id].present?}

  def index
    @event_groups = EventGroup.search(params, @event_groups) if params[:search].present?
    @event_groups = @event_groups.paginate(page: params[:page], per_page: 10)
  end
  def new
    @event_group = @client.event_groups.build
  end
  def create
     @event_group = @client.event_groups.new(event_groups_params)
    if @event_group.save
      redirect_to admin_client_event_groups_path(:client_id => @event_group.client_id)
    else
      render :action => 'new'
    end
  end
  def edit
    
  end
  def update
    if @event_group.update_attributes(event_groups_params)
      redirect_to admin_client_event_groups_path(:client_id => @event_group.client_id)
    else
      render :action => 'edit'
    end
  end
  def destroy
    if @event_group.destroy
      redirect_to admin_client_event_groups_path(:client_id => @event_group.client_id)
    end 
  end
  def show
    
  end

  protected
    def event_groups_params
      params.require(:event_group).permit!
    end  
end

hob_nob/app/helpers/admin/event_groups_helper.rb
module Admin::EventGroupsHelper
end

hob_nob/app/views/admin/event_groups/_form.html.haml
.save_button.mdl-card  
  = form_for [:admin, @client, @event_group], :builder => CustomFormBuilder do |f|
    .mdl-grid.mdl-card.mdl-shadow--1dp
      .mdl-cell--12-col.mdl-cell--12-col-tablet.ml-color--shades-white.m-8
        %h4.heading-border.p-t-10
          General Information
          / %a{:href => 'javascript:void(0);', :class =>'helpTag testhelp'}
          /   what's this?
      = render :partial => "admin/layouts/whats_this_popup", :locals => {:image_name => "event_group_generalInfo.jpg", :section_id => "event_group_general_section"} 
      = f.custom_text_field :name, "Name"
      = f.custom_text_area_field :remarks,"Remarks"
    .fixed-activon-btn-new
      = f.custom_submit_button "SAVE"
      .mdl-button.mdl-js-button.mdl-button--raised.mdl-js-ripple-effect.btnsubmit.m-l-18.cancelBg
        .mdl-cell--12-col.mdl-cell--12-col-tablet.cancelbtn
          = back_button(:back)

hob_nob/app/views/admin/event_groups/_index.html.haml
- if !objs.present? and !params[:admin_search].present?
  .mdl-typography--text-center.BlnkTxt.p-t-10
    = index_nodata_message("event_groups")
    - if current_user.has_role? :licensee_admin or current_user.has_role? :client_admin
      = link_to "add one now.",new_admin_client_event_group_path(:client_id => @client.id,:type=>"general"),:class => "centerAlign"
-elsif !objs.present? and params[:admin_search].present?
  .mdl-typography--text-center.BlnkTxt.p-t-10
    = get_search_data("event_groups")
- else  
  %table.table.mdl-data-table.fullwidth.ml-table-striped.ml-table-bordered.font16.ng-scope.ng-table{"template-pagination" => "custom/pager"}
    %tr
      %th Name
      %th Remarks
      %th
      - if objs.present?
        - objs.each do |event_group|
          %tr
            %td.font16= event_group.name.capitalize rescue nil
            %td.font16= event_group.remarks rescue nil
            %td.IconDrp
              = more_vert_button(event_group.id)
              %ul.mdl-menu.mdl-menu--bottom-right.mdl-js-menu.mdl-js-ripple-effect{:for => "demo-menu-lower-right#{event_group.id}"}
                = link_to edit_admin_client_event_group_path(event_group.client_id, event_group.id, :type => "general"),:class => "mdl-menu__item" do
                  Edit
                = link_to admin_client_event_group_path(event_group.client_id, event_group.id),:method => :delete,:class => "mdl-menu__item" do
                  Delete
               

hob_nob/app/views/admin/event_groups/_search.html.haml
.mdl-cell.mdl-cell--6-col.mdl-cell--12-col-tablet.mdl-cell--12-col-phone.newsearchlaypout.HideTabularData
  = form_tag  admin_client_event_groups_path(:client_id => params[:client_id]), :method => :get do
    .mdl-js-textfield.mdl-textfield--floating-label.mdl-grid.f-right.m-r-20.m-t-10 
      #select-container.mdl-textfield.mdl-js-textfield.mdl-textfield--floating-label.mdl-cell--6-col.mdl-cell--5-col-tablet.mdl-cell--12-col-phone
      /   = custom_basic_text_field_tag "search""[keyword]", "", basic_search_value(params)
      /   = hidden_field_tag :admin_search, "true"
      / = custom_basic_button_tag "SEARCH"

hob_nob/app/views/admin/event_groups/edit.html.haml
= render :partial => 'layouts/layout_form', :locals => {:page => 'Edit Event Group'}

hob_nob/app/views/admin/event_groups/index.html.haml
= render :partial => 'admin/layouts/index_header', :locals => {:objs => @event_groups}

hob_nob/app/views/admin/event_groups/new.html.haml
= render :partial => 'layouts/layout_form', :locals => {:page => 'New Event Group'}