hob_nob/config/routes.rb
Rails.application.routes.draw do

  match "/404", :to => "errors#not_found", :via => :all
  
  match "/500", :to => "errors#internal_server_error", :via => :all


  
mount Ckeditor::Engine => '/ckeditor'
devise_for :users
as :user do
  get 'passwords/change_password' => 'devise/passwords#edit'
  put 'passwords' => 'devise/passwords#update'
end
#root "admin/dashboards#index"
root "admin/homes#index"
get 'back' => 'application#back'

resources :custom_pages

resources :events, :controller => "microsites", :as => "microsites"
resources :events do
  resources :custom_pages
end

namespace :admin do
  get 'bee_editor' => 'bee_editors#index'
  get '/mobile_applications/:mobile_application_id/success' => 'external_login#show'
  get '/events/:event_id/success' => 'user_registrations#show'
  get '/unsubscribes/success' => 'unsubscribes#show'
  get '/unsubscribes' => 'unsubscribes#index'
  get 'bee_editor/token' => 'bee_editors#token'
  get 'bee_editor/template' => 'bee_editors#template'
    
  # get '/check_email_existance' => 'users#check_email_existance'
  resources :time_zones, :notification_action_changes
  resources :dashboards, :themes, :manage_users, :users, :roles, :homes, :smtp_settings, :log_changes
  resources :profiles, :manage_mobile_apps, :downloads, :external_login, :prohibited_accesses, :change_roles, :icon_libraries
  resources :licensees do
    resources :clients    
  end
  resources :clients do
    resources :users, :marketing_apps
    resources :mobile_applications do
      resources :push_pem_files
    end
    resources :event_groups
    resources :events
    resources :fonts, except: [:show, :edit, :update]
  end
  resources :mobile_applications do
    resources :external_login
  end

  resources :events do
    resources :microsites do
      resources :microsite_look_and_feels, :microsite_features, :microsite_menus, :microsite_sequences
    end
  end

  resources :events do
    resources :abouts, :event_highlights, :emergency_exits, :themes, :sequences,:leaderboards, :chats, :invitee_groups, :qr_code_scanners, :qr_code_texts, :warehouse_timers,:qna_walls,:conversation_walls,:poll_walls,:quiz_walls, :activity_feeds, :feedback_forms, :export_qr_codes, :badge_pdfs, :microsites
    resources :speakers, :attendees, :invitees, :agendas, :conversations, :users, :notifications
    resources :event_features, :menus, :faqs, :images, :highlight_images, :feedbacks, :sponsors, :qnas, :feedbacks
    resources :e_kits, :contacts, :panels, :imports, :user_registrations
    resources :groupings, :exhibitors, :manage_feature_status, :analytics, :registration_settings, :custom_page1s, :custom_page2s, :custom_page3s, :custom_page4s, :custom_page5s, :invitee_datas,:my_travels,:manage_invitee_fields,:qna_settings, :qnas, :user_qnas, :feedbacks,:registration_look_and_feels,:registration_details,:auto_status_emails,:telecaller_accessible_columns,:telecaller_dashboards,:telecaller_groups,:campaign_details,:track_links ,:venue_sections,:invitee_accesses,:invitee_searches, :qr_scanner_details,:registration_statistics,:onsite_registrations,:maps, :folders, :consent_questions, :onsite_accessible_columns
    resources :custom_page6s, :custom_page7s, :custom_page8s, :custom_page9s, :custom_page10s, :telecaller_searchs
    resources :telecaller_invitees, :import_data_api
    resources :multi_lng_events, :unsubscribes, :log_changes
    # resources :feedback_forms do
    #   resources :feedbacks
    # end
    resources :feedback_forms,:feedbacks
    
    resources :telecallers do
      collection do
        get :attended_records
      end
    end

    resources :polls do
      resources :user_polls
    end

    resources :quizzes do
      resources :user_quizzes
    end

    # resources :invitee_datas do
    #   collection do
    #     post 'update_details'
    #   end
    # end

    resources :user_polls, :user_quizzes, :user_feedbacks, :likes, :comments

    resources :mobile_applications do
      resources :store_infos
      resources :mobile_consent_questions, :consent_question_look_and_feels
    end  
    resources :awards do
      resources :winners 
    end
    resources :invitee_structures do
      resources :invitee_datas
    end
    resources :registrations
    get '/user_qnas/new/:rid/:sid' => 'user_qnas#new', :as => "receiver_qnas"
    resources :campaigns do
      resources :edms do
        put :toggle_tele_assigned, on: :member
      end
    end
    resources :track_link_users
  end

  # resources :imports
end
# resources :events do
#   resources :microsites 
# end

get "/api/v1/activity_feeds?event_id=:event_id&social=true" => redirect("/api/v1/events/:event_id/social_feeds")
  namespace :api do
    namespace :v1 do
      get 'tokens/destroy_token' => 'tokens#destroy_token', defaults: {format: 'json'}
      post 'tokens/get_key' => 'tokens#get_key'#, defaults: {format: 'json'}
      get 'tokens/check_token' => 'tokens#check_token', defaults: {format: 'json'}
      post 'tokens/user_sign_up' => 'tokens#user_sign_up', defaults: {format: 'json'}
      post 'tokens/facebook_authentication' => 'tokens#facebook_authentication', defaults: {format: 'json'}
      post 'tokens/twitter_authentication' => 'tokens#twitter_authentication', defaults: {format: 'json'}
      resources :events do 
        post 'delete_mobile_data', on: :collection 
        resources :chats do 
          post 'update_chat_read_status', on: :collection # method used for update msg read status for api.
        end
        resources :invitee_chats,:social_feeds  
      end
      resources :tokens, :social_media_authentications, :abouts, :agendas, :speakers, :invitees, :leaderboards, :attendees, :images, :ratings, defaults: {format: 'json'} 
      resources :faqs, :notifications, :conversations, :comments, :qnas, :polls,:invitee_trackings, defaults: {format: 'json'}
      resources :awards, :event_features, :sponsors, :likes, :notes, :user_feedbacks,:e_kits, :mobile_applications, :passwords, :my_travels, defaults: {format: 'json'}
      resources :activity_feeds,:visitor_registrations, :mobile_consent_question_answers
    end
    namespace :v2 do
      resources :events
    end
    namespace :v3 do
      resources :events
    end
    namespace :v4 do
      resources :events
      resources :e_kits
    end
    namespace :v5 do
      resources :events, :conversations, :images, :leaderboards, :invitees
    end
  end
end

hob_nob/app/controllers/admin/event_features_controller.rb
class Admin::EventFeaturesController < ApplicationController
  layout 'admin'

  load_and_authorize_resource
  before_filter :authenticate_user, :authorize_event_role, :find_features
  
  def index
    redirect_to admin_event_menus_path(:event_id => @event.id)
  end

  def new
    if params[:feature] == "my_calender"
      @event_feature = @event.event_features.new
      @event_feature.menu_icon_visibility = nil
    else
      @default_features = @event.set_features_default_list
      @static_features = @event.set_features_static_list
      @present_feature = @event.set_features rescue []
    end  
  end

  def create
    if params[:calender].present?
      calender_setting
      # elsif params[:faq_setting].present?
      #   faq_setting
    elsif params[:image_setting].present?
      image_setting
    else
      if params[:multiple_create].present?
        @event.add_features(params)
        redirect_to admin_event_mobile_application_path(:event_id => @event.id, :id => @event.mobile_application_id)
      else
        if @event.update_attributes(event_params)
          redirect_to admin_event_mobile_application_path(:event_id => @event.id, :id => @event.mobile_application_id)
        else
          render :action => 'index'
        end
      end
    end    
  end

  def update
    # if params[:status].present?
    #   @event_feature.set_status(params[:status])
    #   redirect_to admin_event_menus_path(:event_id => @event.id)
    # end
  end

  def destroy
    # if @event_feature.destroy
    #   redirect_to admin_event_event_features_path(:event_id => @event.id)
    # end
  end

	protected
  def event_params
    params.require(:event).permit! if params[:event].present?
  end
  
  def calender_setting
    if params["event_feature"]["menu_icon_visibility"].blank?
      @feature_error = "This field is required."
      render :action => "new"
    else
      @feature_error = nil
      feature = @event.event_features.where(name: "my_calendar").first rescue []
      params[:event_feature][:menu_icon_visibility] = params[:event_feature][:menu_icon_visibility].downcase rescue ""
      if feature.present?
        feature.update(event_feature_params)
        redirect_to admin_event_agendas_path(:event_id => @event.id)
      else
        @event_feature = @event.event_features.new(event_feature_params)
        if @event_feature.save
          redirect_to admin_event_agendas_path(:event_id => @event.id)
        else
          @event_feature.menu_icon_visibility = nil
          @feature_error = "This field is required."
          render :action => "new"
        end
      end
    end 
  end

  def image_setting
    if params["event_feature"]["image_setting"].blank?
      @feature_error = "This field is required."
      render :action => "new"
    else
      @feature_error = nil
      feature = @event.event_features.where(name: "galleries").first rescue []
      if feature.present?
        feature.update(event_feature_params)
        redirect_url = feature.image_setting == 'Yes' ? admin_event_folders_path(:event_id => @event.id) : admin_event_images_path(:event_id => @event.id)
        redirect_to redirect_url
      else
        @event_feature = @event.event_features.new(event_feature_params)
        if @event_feature.save
          redirect_url = @event_feature.image_setting == 'Yes' ? admin_event_folders_path(:event_id => @event.id) : admin_event_images_path(:event_id => @event.id)
          redirect_to redirect_url
        else
          @event_feature.image_setting = nil
          @feature_error = "This field is required."
          render :action => "new"
        end
      end
    end  
  end

  # def faq_setting
  #   if params["event_feature"]["faq_setting"].blank?
  #     @feature_error = "This field is required."
  #     render :action => "new"
  #   else
  #     @feature_error = nil
  #     feature = @event.event_features.where(name: "faqs").first rescue []
  #     if feature.present?
  #       feature.update(event_feature_params)
  #       redirect_to admin_event_mobile_application_path(:event_id => @event.id, :id => @event.mobile_application.id, :type => "show_content")
  #     else
  #       @event_feature = @event.event_features.new(event_feature_params)
  #       if @event_feature.save
  #         redirect_to admin_event_mobile_application_path(:event_id => @event.id, :id => @event.mobile_application.id, :type => "show_content")
  #       else
  #         @event_feature.faq_setting = nil
  #         @feature_error = "This field is required."
  #         render :action => "new"
  #       end
  #     end
  #   end
  # end

  def event_feature_params
    if params[:event_feature].present?
      params.require(:event_feature).permit! 
    end  
  end
end

hob_nob/app/views/admin/event_features/_form.html.haml
.save_button
  = form_for [:admin, @event, @event_feature], :builder => CustomFormBuilder do |f|
    .mdl-grid.mdl-card.mdl-shadow--1dp.agendaHeight
      .mdl-cell--12-col.mdl-cell--12-col-tablet.ml-color--shades-white.m-8
        %h4.heading-border.m-b-30.p-t-10
          - if params[:feature] == "my_calender"
            General Information
            / - elsif params[:type] == "faq_setting"
            /   General Setting
          - elsif params[:type] == "image_setting"
            General Information
          - else
            Application Features
          / %a{:href => 'javascript:void(0);', :class =>'helpTag testhelp'}
          /   what's this?
        - if @event.present? and @event.event_features.pluck(:name).exclude? 'event_highlights' and @event.login_at == 'After Highlight' 
          .field_with_errors
            .span{:class => "errorMessage"}
              = 'Kindly active Event Highlights feature to set login at After highlights'
      - if params[:feature] == "my_calender"
        .mdl-cell--12-col.mdl-cell--12-col-tablet.ml-color--shades-white.m-8
          .mdl-grid.p-v-5
            .col-lg-4.mdl-typography--text-right
              %p.displayInlineBlock.multicitytxt Allow users to add agenda to calender
            = hidden_field_tag :calender, :value => 'yes'
            = f.hidden_field :name, :value => 'my_calendar'
            = f.hidden_field :page_title, :value => 'My Calendar'
            = f.hidden_field :status, :value => 'deactive'
            = f.hidden_field :menu_visibilty, :value => 'deactive'
            = hidden_field_tag :feature, "my_calender"
            
            .col-lg-7.p-h-12
              = f.custom_radio_button_menu :menu_icon_visibility, "Yes","yes", :id => "option-1",:default_checked => "#{@event.get_event_feature_status == "yes" ? "checked" : "" }"
              = f.custom_radio_button_menu :menu_icon_visibility, "No", "no", :id => "option-2",:default_checked => "#{@event.get_event_feature_status == "no" ? "checked" : "" }"
              - if @feature_error.present?
                .field_with_errors
                  .span{:class => "errorMessage"}
                    = @feature_error rescue nil
          .mdl-grid.p-v-5
            .col-lg-4.mdl-typography--text-right
              %p.displayInlineBlock.multicitytxt Allow adding Individual Sessions to My Agenda
            .col-lg-7.p-h-12
              = f.custom_radio_button_menu :session_to_agenda, "Yes","yes", :id => "option-11", :default_checked => "#{@event.get_event_session_to_my_agenda_status == "yes" ? "checked" : "" }"
              = f.custom_radio_button_menu :session_to_agenda, "No", "no", :id => "option-22", :default_checked => "#{@event.get_event_session_to_my_agenda_status == "no" ? "checked" : "" }"
              - if @feature_error.present?
                .field_with_errors
                  .span{:class => "errorMessage"}
                    = @feature_error rescue nil
                    / -elsif params[:type] == "faq_setting"
                    /   .mdl-cell--12-col.mdl-cell--12-col-tablet.ml-color--shades-white.m-8
                    /     .mdl-grid.p-v-5
                    /       .col-lg-4.mdl-typography--text-right
                    /         %p.displayInlineBlock.multicitytxt You Want to Add Category To FAQ
                    /       .col-lg-7.p-h-12
                    /         = hidden_field_tag :faq_setting, :value => 'yes'
                    /         = f.custom_radio_button_menu :faq_setting, "Yes","yes", :id => "option-3", :default_checked => "#{@event.get_category_faq_setting_status == "yes" ? "checked" : "" }"
                    /         = f.custom_radio_button_menu :faq_setting, "No", "no", :id => "option-4", :default_checked => "#{@event.get_category_faq_setting_status == "no" ? "checked" : "" }"
                    /         - if @feature_error.present?
                    /           .field_with_errors
                    /             .span{:class => "errorMessage"}
                    /               = @feature_error rescue nil
      -elsif params[:type] == "image_setting"
        .mdl-cell--12-col.mdl-cell--12-col-tablet.ml-color--shades-white.m-8
          .mdl-grid.p-v-5
            .col-lg-4.mdl-typography--text-right
              %p.displayInlineBlock.multicitytxt Add Folders to Gallery?
            .col-lg-7.p-h-12
              = hidden_field_tag :image_setting, :value => 'yes'
              = f.custom_radio_button_menu :image_setting, "Yes","yes", :id => "option-3", :default_checked => "#{@event.get_gallery_folder_setting_status == "yes" ? "checked" : "" }"
              = f.custom_radio_button_menu :image_setting, "No", "no", :id => "option-4", :default_checked => "#{@event.get_gallery_folder_setting_status == "no" ? "checked" : "" }"
              - if @feature_error.present?
                .field_with_errors
                  .span{:class => "errorMessage"}
                    = @feature_error rescue nil
      -else
        = render :partial => "admin/layouts/whats_this_popup", :locals => {:image_name => "event_feature_generalInfo.jpg", :section_id => "event_feature_general_section"} 
        - hash_of_feature_list = {"abouts" => "About", "agendas" => "Agenda", "speakers" => "Speakers", "faqs" => "FAQ", "galleries" => "Gallery", "feedbacks" => "Feedback", "e_kits" => "e-KIT", "conversations" => "Conversations", "polls" => "Polls", "awards" => "Awards", "invitees" => "Invitees", "qnas" => "Q&A" , "notes" => "Notes", "contacts" => "Contact Us", "venue" => "Venue", "event_highlights" => "Event Highlights", "highlight_images" => "Highlight Images","sponsors" => "Sponsors", "my_profile" => "My Profile", "qr_code" => "QR Code Scanner", "quizzes" => "Quiz", "favourites" => "My Favourites", "networks" => "My Network","exhibitors" => "Exhibitors", 'leaderboard' => 'Leaderboard', "custom_page1s" => "Custom Page 1", "custom_page2s" => "Custom Page 2", "custom_page3s" => "Custom Page 3", "custom_page4s" => "Custom Page 4", "custom_page5s" => "Custom Page 5", "custom_page6s" => "Custom Page 6", "custom_page7s" => "Custom Page 7", "custom_page8s" => "Custom Page 8", "custom_page9s" => "Custom Page 9", "custom_page10s" => "Custom Page 10", "chats" => "One on One Chat","my_travels" => "My Travel","social_sharings" => "Social Sharing", "activity_feeds" => "Activity Feed","all_events" => "Event Listing","maps" => "Map"} 
        = hidden_field_tag :multiple_create, true
        - @default_features.each do |event_feature|
          .mdl-cell--4-col.mdl-cell--2-col-tablet.mdl-cell--1-col-phone.md-checkbox.m-v-8.checkbox_list
            %label.help-tip{:for => "event_user_ids_#{event_feature}"}
              = check_box_tag "event[features][]", event_feature, @present_feature.include?("#{event_feature}"), :class => "", :id => "event_user_ids_#{event_feature}"
              %span.checkbox 
              = hash_of_feature_list[event_feature]
              %a{:href => '/whats_this/template/fpo.jpg', :class=>"fancybox"} ?

    .fixed-activon-btn-new  
      - if @event.present? and @event.is_parent?
        = f.custom_submit_button "SAVE"
      .mdl-button.mdl-js-button.mdl-button--raised.mdl-js-ripple-effect.btnsubmit.m-l-18.cancelBg
        .mdl-cell--12-col.mdl-cell--12-col-tablet.cancelbtn
          = back_button(:back)
    - if false
      .mdl-grid.mdl-card.mdl-shadow--1dp.m-t-40.coomingsoonCard
        .mdl-cell--12-col.mdl-cell--12-col-tablet.ml-color--shades-white.m-8
          %h4.heading-border.m-b-30.p-t-10
            Coming Soon
            / %a{:href => 'javascript:void(0);', :class =>'helpTag testhelp'}
            /   what's this?
          - hash_of_feature_list = {"mycalendar" => "My Calendar", "chat" => "Chat", "travel" => "Travel", "travel" => "Travel", "exhibitionguide" => "Exhibition Guide"} 
          - @static_features.each do |event_feature|
            .mdl-cell--4-col.mdl-cell--2-col-tablet.mdl-cell--1-col-phone.md-checkbox.m-v-8
              %label{:for => "event_user_ids_#{event_feature}"}
                = check_box_tag "event[features][]", event_feature, @present_feature.include?("#{event_feature}"), :class => "", :id => "event_user_ids_#{event_feature}"
                %span.checkbox 
                = hash_of_feature_list[event_feature]
- if @event.present? and @event.parent_id.present?
  :javascript
    $(document).ready(function(){
      $(".checkbox_list input:checkbox").attr("disabled", true);
    });                

hob_nob/app/views/admin/event_features/_show.html.haml
%form.ng-pristine.ng-valid{:action => "#"}
  .mdl-grid
    = show_field("EventFeature Name :", obj.name)
    .mdl-cell--5-col.mdl-cell--4-col-tablet.ml-color--shades-white.m-8
      %p.no-m-b
        %strong EventFeature main_icon:
        %span
        = image_tag obj.main_icon.url(:medium)

hob_nob/app/views/admin/event_features/edit.html.haml
/ %section#content
/   / start container
/   .container
/     %section#tab_part
/       .adminHeading
/         %h1 Edit EventFeature
/         .rightBtn
/           = back_button(:back)
/     = render :partial => 'form'
/     = render :partial => 'layouts/right_side_user_event_manage'

hob_nob/app/views/admin/event_features/index.html.haml
%main.mdl-layout__content.mdl-color--grey-100.page.ng-scope               
  %section.tables-data
    .ml-header.relative.clear.mdl-color--light-blue-800
      .mdl-grid.mdl-grid--no-spacing
        .mdl-cell.mdl-cell--6-col.mdl-cell--12-col-tablet
          %h3.mdl-color-text--white.m-t-15.p-l-40.p-v-20 Manage Event Menu
        =# render :partial => 'event_search'
    .mdl-grid.HideSearchBlog
      .p-h-25.ml-card-holder
        =# render :partial => 'event_advance_search'
    .mdl-grid.mdl-grid--no-spacing
      .mdl-cell.mdl-cell--12-col.mdl-cell--12-col-tablet.mdl-cell--12-col-phone
        .p-35.ml-card-holder.ml-card-holder-first.HeaderHeight
          .mdl-card.mdl-shadow--1dp.m-b-30.clients
            .mdl-card__title.mdl-color--light-blue-600.mdl-typography--text-right.displayBlock
              %h2.mdl-card__title-text.mdl-color-text--white.displayBlock.mdl-typography--text-right.displayBlock.mdl-typography--text-right
                = @event.event_features.count rescue nil
                Event Menu
            - if !@event.event_features.present? and !params[:admin_search].present?
              .mdl-typography--text-center.BlnkTxt
                = render :partial => 'admin/layouts/index_no_data_message', :locals => {:title => 'event_features', :url => "/admin/events/#{params[:event_id]}/event_features/new", :msg => 'test'} 
            - else
              = form_for [:admin, @event] ,:url => admin_event_event_features_path(:event_id => @event.id), :method => "post" do |f|
                %table.table.mdl-data-table.fullwidth.ml-table-striped.ml-table-bordered.font16{"template-pagination" => "custom/pager"}
                  %tr
                    %th
                      Name
                    %th
                      Page Title
                    %th 
                      Sequence  
                    %th
                      Drawer Icons(72x72px) png only
                    %th
                      Menu Icons(288x288px) png only
                    %th 
                      Status
                    %th 
                      Message  
                    %th  
                  - count = 0    
                  = f.fields_for :event_features do |builder| 
                    %tr
                      %td.fond15
                        = Client.display_hsh[builder.object.name] rescue nil
                      %td
                        .mdl-cell--6-col.mdl-cell--6-col-tablet
                          .mdl-textfield.mdl-js-textfield.mdl-textfield--floating-label
                            = builder.text_field :page_title, :class => 'mdl-textfield__input'
                            %label.mdl-textfield__label{:for => "sample5"} Page Title 
                      %td 
                        .mdl-cell--6-col.mdl-cell--6-col-tablet
                          .mdl-textfield.mdl-js-textfield.mdl-textfield--floating-label
                            = builder.text_field :sequence, :class => 'mdl-textfield__input',:id => "samplesequence"
                            %label.mdl-textfield__label{:for => "sample5"} Sequence  
                        
                      %td
                        .mdl-grid.mdl-grid--no-spacing
                          .mdl-cell--4-col.mdl-cell--4-col-tablet
                            .mdl-textfield.mdl-js-textfield.mdl-textfield--floating-label.disableinput
                              = image_tag(builder.object.menu_icon_url(:thumb), :alt =>"")
                          .mdl-cell--2-col.mdl-cell--2-col-tablet.fileUpload.event-imgupload
                            = builder.file_field :menu_icon, :class =>'upload'
                          .mdl-cell--5-col.mdl-cell--5-col-tablet
                            %label.mdl-textfield.mdl-js-textfield.mdl-textfield--floating-label{:class => "event_event_features_attributes_#{count}_menu_icon"}= builder.object.menu_icon_file_name
                      %td
                        .mdl-grid.mdl-grid--no-spacing
                          .mdl-cell--4-col.mdl-cell--4-col-tablet
                            .mdl-textfield.mdl-js-textfield.mdl-textfield--floating-label.disableinput
                              = image_tag(builder.object.main_icon_url(:thumb), :alt =>"")
                          .mdl-cell--2-col.mdl-cell--2-col-tablet.fileUpload.event-imgupload
                            = builder.file_field :main_icon, :class =>'upload'
                          .mdl-cell--5-col.mdl-cell--5-col-tablet
                            %label.mdl-textfield.mdl-js-textfield.mdl-textfield--floating-label{:class => "event_event_features_attributes_#{count}_main_icon"}= builder.object.main_icon_file_name
                      %td.fond15
                        .menustatusnew
                          = builder.object.status
                      %td 
                        .mdl-textfield.mdl-js-textfield.mdl-textfield--floating-label
                          - if builder.object.status == "deactive"   
                            = builder.text_field :description, :class => 'mdl-textfield__input'
                            %label.mdl-textfield__label{:for => "sample5"} Message
                      %td
                        .mdl-cell--1-col.mdl-cell--1-col-tablet  
                          = more_vert_button(builder.object.id)
                          %ul.mdl-menu.mdl-menu--bottom-right.mdl-js-menu.mdl-js-ripple-effect{:for => "demo-menu-lower-right#{builder.object.id}"}
                            - builder.object.aasm.events.each do |eve|
                              = link_to "#{eve.name.to_s.titlecase}".html_safe,{:action=>"update", :controller=>"admin/event_features", :id => builder.object.id, :status => eve.name.to_s, :page => params[:page]}, :method => "put", :data => { confirm: 'Are you sure, you want to change the status.'},:class => "mdl-menu__item"
                            = link_to admin_event_event_feature_path(:event_id =>f.object.id, :id => builder.object.id),method: :delete,:class => "mdl-menu__item" do
                              Remove
                          - count = count + 1      
                      = hidden_field_tag :edit_feature, "true"  
                .mdl-button.mdl-js-button.mdl-button--raised.mdl-color--light-blue-800.mdl-js-ripple-effect.btnsubmit.m-l-18.m-t-10
                  = f.submit "SAVE"

hob_nob/app/views/admin/event_features/new.html.haml
= render :partial => 'layouts/layout_form', :locals => {:page => 'Features'}

hob_nob/app/views/admin/event_features/show.html.haml
= render :partial => "layouts/show_header", :locals => {:obj => @eventFeature,:title => @eventFeature.name}