hob_nob/config/routes.rb
Rails.application.routes.draw do

  match "/404", :to => "errors#not_found", :via => :all
  
  match "/500", :to => "errors#internal_server_error", :via => :all


  
mount Ckeditor::Engine => '/ckeditor'
devise_for :users
as :user do
  get 'passwords/change_password' => 'devise/passwords#edit'
  put 'passwords' => 'devise/passwords#update'
end
#root "admin/dashboards#index"
root "admin/homes#index"
get 'back' => 'application#back'

resources :custom_pages

resources :events, :controller => "microsites", :as => "microsites"
resources :events do
  resources :custom_pages
end

namespace :admin do
  get 'bee_editor' => 'bee_editors#index'
  get '/mobile_applications/:mobile_application_id/success' => 'external_login#show'
  get '/events/:event_id/success' => 'user_registrations#show'
  get '/unsubscribes/success' => 'unsubscribes#show'
  get '/unsubscribes' => 'unsubscribes#index'
  get 'bee_editor/token' => 'bee_editors#token'
  get 'bee_editor/template' => 'bee_editors#template'
    
  # get '/check_email_existance' => 'users#check_email_existance'
  resources :time_zones, :notification_action_changes
  resources :dashboards, :themes, :manage_users, :users, :roles, :homes, :smtp_settings, :log_changes
  resources :profiles, :manage_mobile_apps, :downloads, :external_login, :prohibited_accesses, :change_roles, :icon_libraries
  resources :licensees do
    resources :clients    
  end
  resources :clients do
    resources :users, :marketing_apps
    resources :mobile_applications do
      resources :push_pem_files
    end
    resources :event_groups
    resources :events
    resources :fonts, except: [:show, :edit, :update]
  end
  resources :mobile_applications do
    resources :external_login
  end

  resources :events do
    resources :microsites do
      resources :microsite_look_and_feels, :microsite_features, :microsite_menus, :microsite_sequences
    end
  end

  resources :events do
    resources :abouts, :event_highlights, :emergency_exits, :themes, :sequences,:leaderboards, :chats, :invitee_groups, :qr_code_scanners, :qr_code_texts, :warehouse_timers,:qna_walls,:conversation_walls,:poll_walls,:quiz_walls, :activity_feeds, :feedback_forms, :export_qr_codes, :badge_pdfs, :microsites
    resources :speakers, :attendees, :invitees, :agendas, :conversations, :users, :notifications
    resources :event_features, :menus, :faqs, :images, :highlight_images, :feedbacks, :sponsors, :qnas, :feedbacks
    resources :e_kits, :contacts, :panels, :imports, :user_registrations
    resources :groupings, :exhibitors, :manage_feature_status, :analytics, :registration_settings, :custom_page1s, :custom_page2s, :custom_page3s, :custom_page4s, :custom_page5s, :invitee_datas,:my_travels,:manage_invitee_fields,:qna_settings, :qnas, :user_qnas, :feedbacks,:registration_look_and_feels,:registration_details,:auto_status_emails,:telecaller_accessible_columns,:telecaller_dashboards,:telecaller_groups,:campaign_details,:track_links ,:venue_sections,:invitee_accesses,:invitee_searches, :qr_scanner_details,:registration_statistics,:onsite_registrations,:maps, :folders, :consent_questions, :onsite_accessible_columns
    resources :custom_page6s, :custom_page7s, :custom_page8s, :custom_page9s, :custom_page10s, :telecaller_searchs
    resources :telecaller_invitees, :import_data_api
    resources :multi_lng_events, :unsubscribes, :log_changes
    # resources :feedback_forms do
    #   resources :feedbacks
    # end
    resources :feedback_forms,:feedbacks
    
    resources :telecallers do
      collection do
        get :attended_records
      end
    end

    resources :polls do
      resources :user_polls
    end

    resources :quizzes do
      resources :user_quizzes
    end

    # resources :invitee_datas do
    #   collection do
    #     post 'update_details'
    #   end
    # end

    resources :user_polls, :user_quizzes, :user_feedbacks, :likes, :comments

    resources :mobile_applications do
      resources :store_infos
      resources :mobile_consent_questions, :consent_question_look_and_feels
    end  
    resources :awards do
      resources :winners 
    end
    resources :invitee_structures do
      resources :invitee_datas
    end
    resources :registrations
    get '/user_qnas/new/:rid/:sid' => 'user_qnas#new', :as => "receiver_qnas"
    resources :campaigns do
      resources :edms do
        put :toggle_tele_assigned, on: :member
      end
    end
    resources :track_link_users
  end

  # resources :imports
end
# resources :events do
#   resources :microsites 
# end

get "/api/v1/activity_feeds?event_id=:event_id&social=true" => redirect("/api/v1/events/:event_id/social_feeds")
  namespace :api do
    namespace :v1 do
      get 'tokens/destroy_token' => 'tokens#destroy_token', defaults: {format: 'json'}
      post 'tokens/get_key' => 'tokens#get_key'#, defaults: {format: 'json'}
      get 'tokens/check_token' => 'tokens#check_token', defaults: {format: 'json'}
      post 'tokens/user_sign_up' => 'tokens#user_sign_up', defaults: {format: 'json'}
      post 'tokens/facebook_authentication' => 'tokens#facebook_authentication', defaults: {format: 'json'}
      post 'tokens/twitter_authentication' => 'tokens#twitter_authentication', defaults: {format: 'json'}
      resources :events do 
        post 'delete_mobile_data', on: :collection 
        resources :chats do 
          post 'update_chat_read_status', on: :collection # method used for update msg read status for api.
        end
        resources :invitee_chats,:social_feeds  
      end
      resources :tokens, :social_media_authentications, :abouts, :agendas, :speakers, :invitees, :leaderboards, :attendees, :images, :ratings, defaults: {format: 'json'} 
      resources :faqs, :notifications, :conversations, :comments, :qnas, :polls,:invitee_trackings, defaults: {format: 'json'}
      resources :awards, :event_features, :sponsors, :likes, :notes, :user_feedbacks,:e_kits, :mobile_applications, :passwords, :my_travels, defaults: {format: 'json'}
      resources :activity_feeds,:visitor_registrations, :mobile_consent_question_answers
    end
    namespace :v2 do
      resources :events
    end
    namespace :v3 do
      resources :events
    end
    namespace :v4 do
      resources :events
      resources :e_kits
    end
    namespace :v5 do
      resources :events, :conversations, :images, :leaderboards, :invitees
    end
  end
end

hob_nob/app/controllers/admin/user_registrations_controller.rb
class Admin::UserRegistrationsController < ApplicationController
	# layout 'admin'

  before_filter :find_event
  skip_before_filter :authenticate_user, :load_filter
  before_filter :authenticate_user, :only => [:index] 
  before_filter :find_registration_look_and_feels, only: [:new, :show, :create, :edit, :update]
  
  def index
    if (params[:my_status].present? and params[:my_status] == "Delete") and params[:registration_ids].present?
      params[:registration_ids].uniq.each do |i|
        user_registration = UserRegistration.find(i)
        user_registration.destroy
      end
      return redirect_to admin_event_user_registrations_path(:event_id => @event.id)
    end
    if params[:my_status].present?  and params[:registration_ids].present?
      params[:registration_ids].each do |i|
        user_registration = UserRegistration.find(i)
        status = params[:my_status].downcase.parameterize.underscore
        user_registration.update_column(:status, status)
      end
      return redirect_to admin_event_user_registrations_path(:event_id => @event.id)
    end
    @user_registration = @event.user_registrations.build
    @registration = @event.registrations.first
    if params["format"] == "xls" and params[:type].present? and params[:type] =="total"
      @user_registrations = @event.user_registrations
    else 
      @user_registrations = (params["format"].present? and params["format"] == "xls") ? (params["type"].present? ? @event.user_registrations.where(:status=>"#{params[:type]}") : @event.user_registrations) : @event.user_registrations.paginate(page: params[:page], per_page: 10)
    end
    respond_to do |format|
      format.html do
        @user_registrations = @user_registrations.paginate(page: params[:page], per_page: 10)
        render :layout => 'admin'
      end 
      if @registration.present? and params[:sample_download].present?
        format.xls do
          only_columns = @registration.selected_column_values
          method_allowed = [:timestamp]
          send_data [only_columns,method_allowed].to_reports_xls
        end
      else
        format.xls do
          @export_array = [@registration.selected_column_values.push("Status","Timestamp","Consent Question 1", "Consent Answer 1", "Consent Question 2", "Consent Answer 2", "Consent Question 3", "Consent Answer 3", "Consent Question 4", "Consent Answer 4", "Consent Question 5", "Consent Answer 5", "Consent Question 6", "Consent Answer 6", "Consent Question 7", "Consent Answer 7", "Consent Question 8", "Consent Answer 8", "Consent Question 9", "Consent Answer 9", "Consent Question 10", "Consent Answer 10", "Consent Question Timestamp").unshift("Registration ID")]
          method_allowed = []
          @only_columns = @registration.selected_columns
          @only_columns = @only_columns.push("status","timestamp")
          @consent_questions = ["consent_question_1", "consent_answer_1", "consent_question_2", "consent_answer_2", "consent_question_3", "consent_answer_3", "consent_question_4", "consent_answer_4", "consent_question_5", "consent_answer_5", "consent_question_6", "consent_answer_6", "consent_question_7", "consent_answer_7", "consent_question_8", "consent_answer_8", "consent_question_9", "consent_answer_9", "consent_question_10", "consent_answer_10", "date_timestamp"]
          for invitee in @user_registrations
            if invitee.id.present?
              timestamp = invitee.timestamp
              arr = @only_columns.map{|c|(invitee.attributes[c].present? ? invitee.attributes[c] + (invitee.text_box_for_checkbox_or_radiobutton.present? ? (invitee.text_box_for_checkbox_or_radiobutton[c].blank? ? "" : (" , " + invitee.text_box_for_checkbox_or_radiobutton[c][0].to_s)) : "" ) : "")}
              arr.last << timestamp
              arr.unshift(invitee.id)
              arr1 = @consent_questions.map{|c| invitee.attributes[c]}
              arr1.pop
              arr1 << invitee.consent_ques_answered_timezone
              @export_array << arr + arr1
            end 
          end
          send_data @export_array.to_reports_xls, filename: "registered_user_#{@registration.id}.xls"
        end
      end
    end
  end

  def new
    # if Rails.application.routes.recognize_path(request.referrer)[:controller] == "admin/registrations" 
    #   @custom_registration  = @registration.custom_source_code
    if params[:import].present?
      @import = Import.new
      render :layout => "admin"
    end
    if @event.registrations.present?
      @registration = @event.registrations.first 
      @user_registration = @event.user_registrations.build
      @registration_setting = @event.registration_settings.first
      if @registration_setting.registration == "hobnob" and @registration_setting.template == "custom"
        render :layout => false #"admin/layouts/user_registration"
      end
    else
      redirect_to admin_dashboards_path
    end
  end

  def create
    @registration = @event.registrations.first
    @registration_setting = @event.registration_settings.first

    @existing_user = UserRegistration.find_by(@registration.attributes["email_field"].downcase => params["user_registration"][@registration.attributes["email_field"].downcase], :event_id => params["event_id"]) if params["user_registration"][@registration.attributes["email_field"].downcase].present?
    if @existing_user.present?
      @user_registration = @existing_user
      @user_registration.assign_attributes(user_registration_params)
    else
      @user_registration = @event.user_registrations.build(user_registration_params)
    end  
    if @user_registration.save
      edm = Campaign.find_by_id(0).edms.where(:mail_to => @user_registration.status,:event_id => @user_registration.event_id).first
      edm.send_mail_to_register_user(@user_registration) if edm.present?  
      if @user_registration.walk_in_registration.present? and @user_registration.walk_in_registration == true
        @user_name = @event.badge_pdf.reg_match_name_field if @event.badge_pdf.present?
        if ["approved","confirmed"].include?(@user_registration.status)#@user_registration.status =="confirmed"
          @user_registration.update_columns(qr_code_registration:true, qr_code_registration_time:Time.now, updated_at:Time.now)
        end
        respond_to do |format|
          format.js
        end
      else
        if @user_registration.walk_in_registration.present? and @user_registration.walk_in_registration == true
          @user_name = @event.badge_pdf.reg_match_name_field if @event.badge_pdf.present?
          if ["approved","confirmed"].include?(@user_registration.status)#@user_registration.status =="confirmed"
            @user_registration.update_columns(qr_code_registration:true, qr_code_registration_time:Time.now, updated_at:Time.now)
          end
          respond_to do |format|
            format.js
          end
        else
          return redirect_to admin_event_user_registration_path(:event_id => @event.id,:id => @user_registration.id)
        end
      end
    else
      if @event.registration_settings.first.template == "custom" and params[:action] == "create"
        @registration_setting = @event.registration_settings.first
        render :action => 'new',:layout => "admin/layouts/user_registration.html.haml"
      elsif @user_registration.walk_in_registration.present? and @user_registration.walk_in_registration == true
        respond_to do |format|
          format.js
        end
      else
        render :action => 'new'
      end
    end
  end

  def show
    @message = (@registration_look_and_feel.present? && @registration_look_and_feel.thank_text.present?) ? @registration_look_and_feel.thank_text : 'User Registration Successful'
    @user_registration = UserRegistration.find_by_id(params[:id])
    @registration = @event.registrations.first
  end


  def edit 
    @user_registration = UserRegistration.find_by_id(params[:id])
    @registration = @event.registrations.first
    @registration_look_and_feel = @event.registration_look_and_feels.first if @event.registration_look_and_feels.present?
    @registration_setting = @event.registration_settings.first
    # render :layout => false
  end  

  def update
    @update = true
    @registration = @event.registrations.first
    @registration_setting = @event.registration_settings.first
    @registration_look_and_feel = @event.registration_look_and_feels.first if @event.registration_look_and_feels.present?
    if params[:from] == "all_listing"
      @user_registration = UserRegistration.find(params[:id])
      if @user_registration.update_attributes(user_registration_params.merge(mandate_empty_field))
        render :text => "<script>window.close();window.opener.location.href = window.opener.location.href</script>"
      else
        render action: 'edit'
      end
    elsif params[:onsite_form].present? and params[:onsite_form] == "true"
      @user_registration = UserRegistration.find(params[:id])
      if @user_registration.update_attributes(user_registration_params)
        unless @event.badge_pdf.skip_print
          redirect_to admin_event_qr_code_scanners_path(event_id: @event.id, user_registration_id: @user_registration.id, page: 'print_preview', from: 'invitee_search')
        else
          request.xhr? ? (render text: 'true') : (redirect_to :back)
        end
      else
        request.xhr? ? (render text: 'false') : (redirect_to :back)
      end
    else  
      @user_registrations = @event.user_registrations
      @user_registration = @user_registrations.find_by_id(params[:id])
      @user_registrations = @user_registrations.paginate(page: params[:page], per_page: 10)
      @user_registration.perform_event(params[:status]) if params[:status].present? and params[:manual_approve].present? and params[:manual_approve] == 'true'
      redirect_to :back
    end
    # redirect_to admin_event_user_registrations_path(:event_id => @user_registration.event_id)
  end

  def destroy

hob_nob/app/helpers/user_registrations_helper.rb
module UserRegistrationsHelper
  def check_box_conditions(key, option)
    (params.key?(:user_registration).present? and params[:user_registration][key].include?(option)) || @user_registration.send(key).try(:include?, option) ? 'checked' : false rescue false
  end
end

hob_nob/app/views/admin/user_registrations/_form.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Hobnob
    = favicon_link_tag 'fevicon.png'
    %meta{:content => "width=device-width, initial-scale=1.0, user-scalable=0", :name => "viewport"}/
    %link{:href => "/assets/main_look_and_fill.css", :rel => "stylesheet", :type => "text/css"}/
    %link{:href => "/assets/look_and_fill_responsive.css", :rel => "stylesheet", :type => "text/css"}/
    - @font_hash.each do |hash|
      - if hash.has_key? :url
        :css
          @font-face {
            font-family: "#{hash[:font_name]}";
            src: url("#{hash[:url][0]}") format("#{hash[:format]}"),
                 url("#{hash[:url][1]}") format("#{hash[:format]}");
          }
  - if @registration_look_and_feel.present? and @registration_look_and_feel.body_background_image_file_name.present?
    %body{:style=>"background-image:url(#{@registration_look_and_feel.body_background_image.url});", :class => "dynamic-user-form"}
      - if @registration_look_and_feel.logo_back_color.present? or @registration_look_and_feel.logo_file_name.present?
        %header.header{:style => "background-color:#{@registration_look_and_feel.logo_back_color}"}
          - if params[:show_buttons].present? and params[:show_buttons] == "true"
            .emailer_button{:style => "float:right;margin-right:28px;margin-top:15px;"}
              = link_to "Edit", edit_admin_event_registration_look_and_feel_path(:event_id => @event.id, :id=>@registration_look_and_feel.id),{:style => "background:#1cb1ba;color:#fff;padding:6px 8px;text-decoration:none;"}
              = link_to "Save", admin_event_user_registrations_path(:event_id => @event.id),{:style => "background:#4d4e4f;color:#fff;padding:6px 8px;text-decoration:none;"}
          .container
            .brand-logo{:style=>"float:#{@registration_look_and_feel.logo_alignment}"}
              - if @registration_look_and_feel.logo_file_name.present?
                = image_tag(@registration_look_and_feel.logo.url, :width=>"auto")#,:style => "float:#{@registration_look_and_feel.logo_alignment}")
              - else
                / %img{:src => "/assets/brand-logo.png"}/
      .container
        .form-banner
          - if @registration_look_and_feel.banner_image_file_name.present?
            = image_tag(@registration_look_and_feel.banner_image.url(:large))
            .header-inner
              - if @registration_look_and_feel.header_formatter.present?
                %p
                  = @registration_look_and_feel.header_formatter.html_safe
          - else
      - if (DateTime.now + @event.timezone_offset.seconds).between?(@registration_setting.start_date, @registration_setting.end_date)
        .form_Section
          .container.bgfff
            = render :partial => 'user_registraion_form'
      - else
        .registration_msg
          = @registration_look_and_feel.submit_msg.html_safe rescue nil
      %footer
        - if @registration_look_and_feel.footer_color.present? or @registration_look_and_feel.footer_image.present? or @registration_look_and_feel.footer_formatter.html_safe.present?
          - #if @registration_look_and_feel.footer_image.present? or @registration_look_and_feel.footer_formatter.html_safe.present?
          .container.box-shadow-block{:style => "background-color:#{@registration_look_and_feel.footer_color}"}
            .bottom.clear.clearfix
              .copyright.cvent-footer
                .cvent-footer-wrapper
                  %a{:href => "http://www.cvent.com/", :target => "_blank"}
                    - if  @registration_look_and_feel.present? and @registration_look_and_feel.footer_image_file_name.present?
                      = image_tag(@registration_look_and_feel.footer_image.url(:small))
                    - else
                  - if @registration_look_and_feel.present? and @registration_look_and_feel.footer_formatter.present?
                    = @registration_look_and_feel.footer_formatter.html_safe
                %p
  - elsif @registration_look_and_feel.present? and @registration_look_and_feel.body_background_color.present?
    %body{:style => "background-color:#{@registration_look_and_feel.body_background_color}; ", :class => "dynamic-user-form"}
      - if @registration_look_and_feel.logo_back_color.present? or @registration_look_and_feel.logo_file_name.present?
        %header.header{:style => "background-color:#{@registration_look_and_feel.logo_back_color}"}
          - if params[:show_buttons].present? and params[:show_buttons] == "true"
            .emailer_button{:style => "float:right;margin-right:28px;margin-top:15px;"}
              = link_to "Edit", edit_admin_event_registration_look_and_feel_path(:event_id => @event.id, :id=>@registration_look_and_feel.id),{:style => "background:#1cb1ba;color:#fff;padding:6px 8px;text-decoration:none;"}
              = link_to "Save", admin_event_user_registrations_path(:event_id => @event.id),{:style => "background:#4d4e4f;color:#fff;padding:6px 8px;text-decoration:none;"}
          .container
            .brand-logo{:style=>"float:#{@registration_look_and_feel.logo_alignment}"}
              - if @registration_look_and_feel.logo_file_name.present?
                = image_tag(@registration_look_and_feel.logo.url, :width=>"auto")#,:style => "float:#{@registration_look_and_feel.logo_alignment}")
              - else
                / %img{:src => "/assets/brand-logo.png"}/
      .container
        .form-banner
          - if @registration_look_and_feel.banner_image_file_name.present?
            = image_tag(@registration_look_and_feel.banner_image.url(:large))
            .header-inner
              - if @registration_look_and_feel.header_formatter.present?
                %p
                  = @registration_look_and_feel.header_formatter.html_safe
          - else
      - if (DateTime.now + @event.timezone_offset.seconds).between?(@registration_setting.start_date, @registration_setting.end_date)
        .form_Section
          .container.bgfff
            = render :partial => 'user_registraion_form'
      - else
        .registration_msg
          = @registration_look_and_feel.submit_msg.html_safe rescue nil
      %footer
        - if @registration_look_and_feel.footer_color.present? or @registration_look_and_feel.footer_image.present? or @registration_look_and_feel.footer_formatter.html_safe.present?
          - #if @registration_look_and_feel.footer_image.present? or @registration_look_and_feel.footer_formatter.html_safe.present?
          .container.box-shadow-block{:style => "background-color:#{@registration_look_and_feel.footer_color}"}
            .bottom.clear.clearfix
              .copyright.cvent-footer
                .cvent-footer-wrapper
                  %a{:href => "http://www.cvent.com/", :target => "_blank"}
                    - if  @registration_look_and_feel.present? and @registration_look_and_feel.footer_image_file_name.present?
                      = image_tag(@registration_look_and_feel.footer_image.url(:small))
                    - else
                  - if @registration_look_and_feel.present? and @registration_look_and_feel.footer_formatter.present?
                    = @registration_look_and_feel.footer_formatter.html_safe
                  %p
  - else #@registration_look_and_feel.body_background_image_file_name.present?
    %body{:style=>"background-image:url(#{@registration_look_and_feel.body_background_image.url}); ", :class => "dynamic-user-form"}
      - if @registration_look_and_feel.logo_back_color.present? or @registration_look_and_feel.logo_file_name.present?
        %header.header{:style => "background-color:#{@registration_look_and_feel.logo_back_color}"}
          - if params[:show_buttons].present? and params[:show_buttons] == "true"
            .emailer_button{:style => "float:right;margin-right:28px;margin-top:15px;"}
              = link_to "Edit", edit_admin_event_registration_look_and_feel_path(:event_id => @event.id, :id=>@registration_look_and_feel.id),{:style => "background:#1cb1ba;color:#fff;padding:6px 8px;text-decoration:none;"}
              = link_to "Save", admin_event_user_registrations_path(:event_id => @event.id),{:style => "background:#4d4e4f;color:#fff;padding:6px 8px;text-decoration:none;"}
          .container
            .brand-logo{:style=>"float:#{@registration_look_and_feel.logo_alignment}"}
              - if @registration_look_and_feel.present? and @registration_look_and_feel.logo_file_name.present?
                = image_tag(@registration_look_and_feel.logo.url, :width=>"auto")#,:style => "float:#{@registration_look_and_feel.logo_alignment}")
              - else
                / %img{:src => "/assets/brand-logo.png"}/
      .container
        .form-banner
          - if @registration_look_and_feel.present? and @registration_look_and_feel.banner_image_file_name.present?
            = image_tag(@registration_look_and_feel.banner_image.url(:large))
            .header-inner
              - if @registration_look_and_feel.header_formatter.present?
                %p
                  = @registration_look_and_feel.header_formatter.html_safe
          - else
            / %img{:src => "/assets/form-banner.jpg"}/
      - if (DateTime.now + @event.timezone_offset.seconds).between?(@registration_setting.start_date, @registration_setting.end_date)
        .form_Section
          .container.bgfff
            = render :partial => 'user_registraion_form'
      - else
        .registration_msg
          = @registration_look_and_feel.submit_msg.html_safe rescue nil
      %footer
        - if @registration_look_and_feel.footer_color.present? or @registration_look_and_feel.footer_image.present? or @registration_look_and_feel.footer_formatter.html_safe.present?
          - #if @registration_look_and_feel.footer_image.present? or @registration_look_and_feel.footer_formatter.html_safe.present?
          .container.box-shadow-block{:style => "background-color:#{@registration_look_and_feel.footer_color}"}
            .bottom.clear.clearfix
              .copyright.cvent-footer
                .cvent-footer-wrapper
                  %a{:href => "http://www.cvent.com/", :target => "_blank"}
                    - if  @registration_look_and_feel.present? and @registration_look_and_feel.footer_image_file_name.present?
                      = image_tag(@registration_look_and_feel.footer_image.url(:small))
                    - else
                  - if @registration_look_and_feel.present? and @registration_look_and_feel.footer_formatter.present?
                    = @registration_look_and_feel.footer_formatter.html_safe
:css
  .registration_msg {text-align: center;}

hob_nob/app/views/admin/user_registrations/_user_registration_show.html.haml
.newresitration.agendaHeight.user_reg_form.db
  .mdl-grid.mdl-shadow--1dp.p-b-25.m-b-5
    .mdl-cell--12-col.mdl-cell--12-col-tablet.ml-color--shades-white.m-8
    %h1{ style: "text-align: center;font-family: #{@font_hash[0][:font_name]}"}
      = @message.html_safe
    %table.set_css
      / - if @registration_look_and_feel.present? and  @registration_look_and_feel.registration_form_header.present?
      /   %h4.heading-border.p-t-10.m-b-15{:style => "font-size: #{@registration_look_and_feel.header_font_size}px; font-weight:bold;font-family: #{@registration_look_and_feel.page_font.present? ? @registration_look_and_feel.page_font : ""}" }
      /     = @registration_look_and_feel.registration_form_header.html_safe
      / - @registration.attributes.except('id', 'created_at', 'updated_at', 'event_id', 'custom_css','custom_js', 'custom_source_code','email_field','parent_id').map{|key, value| (value['label'].present? and value['option_type'].present?) ? [key,value] : nil}.compact.each do |key,hsh|
      /   %tr
      /     %td.space
      /       = "#{hsh['label']}" 
      /       %span.show-colon
      /         = ':'   
      /     %td= @user_registration["#{key}"]
      /     - if (hsh["option_type"].present? and ["Radio Button","Check Box","Drop-Down list"].include?(hsh["option_type"]) and (hsh["text_box_required_after_options"].present? and hsh["text_box_required_after_options"] == "yes"))
      /       %tr
      /         %td.space
      /           = "Description"
      /           %span.show-colon
      /             = ':'   
      / %td= @user_registration["text_box_for_checkbox_or_radiobutton"][key].present? ? @user_registration["text_box_for_checkbox_or_radiobutton"][key].first : ""

hob_nob/app/views/admin/user_registrations/create.js.erb
$(".overlayBg").hide();
<% if @user_registration.errors.present? %>
	 <% @user_registration.errors.messages.each do |error_message| %>
    $("#error_field_<%=error_message.first.to_s %>").html("<%=error_message.second.join%>")
    $("#error_field_<%=error_message.first.to_s %>").css('margin-left','35%');
    $("#error_field_<%=error_message.first.to_s %>").css('color','red');
  <% end %>
<% elsif @user_registration.status.present? and ["approved","confirmed"].include?(@user_registration.status) %>
	$(".error-msg-text").css('display','none');
		window.setTimeout(function() {
    	location = window.location.href;
		}, 2000);
	$(".regis_form_msg").html("");
	$(".regis_form_msg").html("Registration created successfully");
	window.open('/admin/events/<%=@event.id%>/qr_code_scanners?user_registration_id=<%=@user_registration.id%>&page=print_preview&walk_in_registration=true', "myWindowName", "width=1000, height=800","about:blank","newwin");
<% else %>
	$(".error-msg-text").css('display','none');
	<% if @user_name.present? %>
		window.setTimeout(function() {
    	location =  window.location.href;
		}, 2000);
		$(".regis_form_msg").html("Registration of <%= @user_registration.send(@user_name)%> is not confirmed");
	<% else %>
	$(".regis_form_msg").html("Registration is not confirmed");
	<% end %>
<% end %>